-- DeployGrade core tenancy, artifact lineage, approval, and Pilot-event model.
create extension if not exists pgcrypto;

create table if not exists organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table if not exists organization_memberships (organization_id uuid not null references organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check (role in ('owner','fde','reviewer','viewer')), primary key (organization_id,user_id));
create table if not exists engagements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, vertical text not null, target_agent text not null, status text not null check (status in ('DISCOVERY','READINESS','BLUEPRINT','PILOT','PAUSED','SCALE','COMPLETE')), created_at timestamptz not null default now());
create table if not exists artifacts (hash text primary key, organization_id uuid not null references organizations(id) on delete cascade, engagement_id uuid references engagements(id) on delete cascade, schema_uri text not null, rubric_version text, rubric_hash text, payload jsonb not null, created_at timestamptz not null default now());
create table if not exists approvals (id uuid primary key default gen_random_uuid(), engagement_id uuid not null references engagements(id) on delete cascade, artifact_hash text not null references artifacts(hash), approved_by uuid not null references auth.users(id), decision text not null check (decision in ('APPROVED','REJECTED')), created_at timestamptz not null default now());
create table if not exists pilot_jobs (id uuid primary key default gen_random_uuid(), engagement_id uuid not null references engagements(id) on delete cascade, blueprint_hash text not null references artifacts(hash), status text not null check (status in ('QUEUED','RUNNING','PAUSED','REVERTED','COMPLETE','FAILED')), sandbox_repository text not null, created_at timestamptz not null default now());
create table if not exists pilot_events (id uuid primary key default gen_random_uuid(), pilot_job_id uuid not null references pilot_jobs(id) on delete cascade, event_type text not null check (event_type in ('PILOT_STARTED','ACTION_DENIED','METRIC_RECORDED','THRESHOLD_BREACHED','ROLLBACK_FIRED','COMPENSATING_REVERTED','PILOT_PAUSED')), artifact_hash text references artifacts(hash), payload jsonb not null, created_at timestamptz not null default now());

alter table organizations enable row level security; alter table organization_memberships enable row level security; alter table engagements enable row level security; alter table artifacts enable row level security; alter table approvals enable row level security; alter table pilot_jobs enable row level security; alter table pilot_events enable row level security;
create policy "member organization access" on organizations for all using (exists (select 1 from organization_memberships m where m.organization_id=id and m.user_id=auth.uid()));
create policy "member engagement access" on engagements for all using (exists (select 1 from organization_memberships m where m.organization_id=engagements.organization_id and m.user_id=auth.uid()));
create policy "member artifact access" on artifacts for all using (exists (select 1 from organization_memberships m where m.organization_id=artifacts.organization_id and m.user_id=auth.uid()));
create policy "member approval access" on approvals for all using (exists (select 1 from engagements e join organization_memberships m on m.organization_id=e.organization_id where e.id=approvals.engagement_id and m.user_id=auth.uid()));
create policy "member pilot job access" on pilot_jobs for all using (exists (select 1 from engagements e join organization_memberships m on m.organization_id=e.organization_id where e.id=pilot_jobs.engagement_id and m.user_id=auth.uid()));
create policy "member pilot event access" on pilot_events for all using (exists (select 1 from pilot_jobs j join engagements e on e.id=j.engagement_id join organization_memberships m on m.organization_id=e.organization_id where j.id=pilot_events.pilot_job_id and m.user_id=auth.uid()));
